const lessonData = {};

lessonData["01_Ainu.mp3"] = [{
    text: `The Ainu are the indigenous people of northern Japan, specifically the island of Hokkaido. For a long time, their culture was a secret. They have a unique language that is not related to Japanese. The Ainu believe that spirits, called "kamuy," live in everything in nature, especially in bears and owls. Historically, Ainu men grew thick beards and women had traditional tattoos around their mouths. They were expert hunters and fishermen. Today, the Ainu work hard to keep their language and traditions alive through music and festivals. They are a symbol of the diverse history of the Japanese islands.`,
    dict: { "indigenous": "yerli", "northern": "kuzey", "specifically": "özellikle", "island": "ada", "long time": "uzun zaman", "culture": "kültür", "secret": "sır", "unique": "eşsiz/benzersiz", "language": "dil", "related": "bağlantılı/akraba", "believe": "inanmak", "spirits": "ruhlar", "called": "adlandırılan", "live": "yaşamak", "everything": "her şey", "nature": "doğa", "especially": "özellikle", "bears": "ayılar", "owls": "baykuşlar", "historically": "tarihsel olarak", "men": "erkekler", "grew": "büyüttü/uzattı", "thick": "kalın/gür", "beards": "sakallar", "women": "kadınlar", "traditional": "geleneksel", "tattoos": "dövmeler", "around": "etrafında", "mouths": "ağızlar", "expert": "uzman", "hunters": "avcılar", "fishermen": "balıkçılar", "today": "bugün", "work": "çalışmak", "hard": "sıkı/zor", "keep": "tutmak/korumak", "traditions": "gelenekler", "alive": "canlı", "through": "aracılığıyla", "music": "müzik", "festivals": "festivaller", "symbol": "sembol", "diverse": "çeşitli", "history": "tarih", "islands": "adalar" },
    questions: [ {q:"Are the Ainu the indigenous people of northern Japan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their culture a secret for a long time?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their language have relation to Japanese?", a_en:"No", a_tr:"Hayır"}, {q:"Do they believe spirits live in bears and owls?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ainu men grow thick beards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did women have tattoos around their eyes?", a_en:"No", a_tr:"Hayır"}, {q:"Do they keep their traditions alive through festivals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_Badjao.mp3"] = [{
    text: `The Badjao are known as "Sea Nomads" because they spend almost their entire lives on the water. They live in houseboats or houses built on stilts over the ocean in the Philippines and Malaysia. Many Badjao are born and live at sea without staying on land for long. Because they dive for fish every day, their bodies have changed; they can see clearly underwater and hold their breath for several minutes. They are some of the best divers in the world. They are peaceful people who move across the ocean following the fish and the seasons.`,
    dict: { "known as": "olarak bilinen", "Sea": "Deniz", "Nomads": "Göçebeler", "because": "çünkü", "spend": "harcarlar/geçirirler", "almost": "neredeyse", "entire": "tüm/bütün", "lives": "hayatlar", "water": "su", "houseboats": "yüzen evler", "built": "inşa edilmiş", "stilts": "kazıklar", "over": "üzerinde", "ocean": "okyanus", "born": "doğmuş", "sea": "deniz", "without": "olmadan", "staying": "kalma", "land": "kara", "long": "uzun süre", "dive": "dalarlar", "fish": "balık", "every day": "her gün", "bodies": "vücutlar", "changed": "değişti", "see": "görmek", "clearly": "açıkça/net", "underwater": "sualtı", "hold": "tutmak", "breath": "nefes", "several": "birkaç", "minutes": "dakikalar", "best": "en iyi", "divers": "dalgıçlar", "world": "dünya", "peaceful": "barışçıl/huzurlu", "people": "insanlar", "move": "hareket etmek", "across": "boyunca", "following": "takip eden", "seasons": "mevsimler" },
    questions: [ {q:"Are the Badjao known as Sea Nomads?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they spend their entire lives on the water?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in houses built on stilts?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make long stays on land?", a_en:"No", a_tr:"Hayır"}, {q:"Can they see clearly underwater?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they hold their breath for only five seconds?", a_en:"No", a_tr:"Hayır"}, {q:"Are they some of the best divers in the world?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_Basque.mp3"] = [{
    text: `The Basque people live in a region between Spain and France. They are a mystery in Europe because their language, "Euskara," is not related to any other language on Earth. No one knows exactly where they came from. They are proud of their identity and have unique sports and music. They are famous for being excellent sailors and for their delicious "pintxos" (small snacks). The Basque culture is very strong, and they have kept their traditions alive for thousands of years despite being surrounded by much larger nations.`,
    dict: { "region": "bölge", "between": "arasında", "mystery": "gizem", "Europe": "Avrupa", "language": "dil", "related": "bağlantılı/akraba", "other": "diğer", "Earth": "Dünya", "knows": "bilir", "exactly": "kesinlikle/tam olarak", "came from": "geldi", "proud": "gururlu", "identity": "kimlik", "unique": "benzersiz", "sports": "sporlar", "music": "müzik", "famous": "ünlü", "excellent": "mükemmel", "sailors": "denizciler", "delicious": "lezzetli", "small": "küçük", "snacks": "atıştırmalıklar", "culture": "kültür", "strong": "güçlü", "kept": "tuttu/korudu", "traditions": "gelenekler", "alive": "canlı", "thousands": "binlerce", "years": "yıllar", "despite": "rağmen", "surrounded": "kuşatılmış", "much": "çok", "larger": "daha büyük", "nations": "uluslar/milletler" },
    questions: [ {q:"Do the Basque people live between Spain and France?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their language related to no other language on Earth?", a_en:"Yes", a_tr:"Evet"}, {q:"Does nobody know exactly where they came from?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they proud of their identity?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for being excellent sailors?", a_en:"Yes", a_tr:"Evet"}, {q:"Are 'pintxos' large, heavy meals?", a_en:"No", a_tr:"Hayır"}, {q:"Have they kept their traditions alive for thousands of years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Bedouin.mp3"] = [{
    text: `The Bedouin are the legendary nomadic people of the Arabian and Saharan deserts. The word "Bedouin" means "desert dweller." For centuries, they have traveled across the dry sands with their camels, goats, and sheep. They live in large black tents made of goat hair. The Bedouin are famous for their incredible hospitality; if a stranger comes to their tent, they will give them food and water for three days. Although many now live in cities, they still feel a deep connection to the desert and their traditional tribal laws.`,
    dict: { "legendary": "efsanevi", "nomadic": "göçebe", "deserts": "çöller", "word": "kelime", "means": "anlamına gelir", "dweller": "sakin/yaşayan", "centuries": "yüzyıllar", "traveled": "seyahat ettiler", "across": "boyunca", "dry": "kuru", "sands": "kumlar", "camels": "develer", "goats": "keçiler", "sheep": "koyunlar", "large": "büyük", "black": "siyah", "tents": "çadırlar", "made of": "yapılmış", "hair": "kıl/saç", "famous": "ünlü", "incredible": "inanılmaz", "hospitality": "misafirperverlik", "stranger": "yabancı", "comes": "gelir", "food": "yiyecek", "water": "su", "days": "günler", "Although": "rağmen", "many": "birçoğu", "now": "şimdi", "cities": "şehirler", "still": "hala", "feel": "hisseder", "deep": "derin", "connection": "bağlantı", "traditional": "geleneksel", "tribal": "kabile", "laws": "yasalar" },
    questions: [ {q:"Are the Bedouin nomadic people of the desert?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the word Bedouin mean 'desert dweller'?", a_en:"Yes", a_tr:"Evet"}, {q:"Have they traveled with camels and goats for centuries?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in blue tents made of cotton?", a_en:"No", a_tr:"Hayır"}, {q:"Are they famous for incredible hospitality?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they give strangers food and water for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many still feel a deep connection to the desert?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_Berbers.mp3"] = [{
    text: `The Berbers, who call themselves the "Amazigh" (meaning free people), are the original inhabitants of North Africa. They live across the mountains and deserts of Morocco, Algeria, and Tunisia. They have a long history that goes back to the time of the Ancient Egyptians. The Berbers are famous for their beautiful silver jewelry, colorful carpets, and unique music. They lived in "Kasbahs," which are massive mud-brick castles. Even today, many Berber families live in the mountains and follow the traditions of their ancestors.`,
    dict: { "themselves": "kendilerini", "meaning": "anlamına gelen", "free": "özgür", "people": "insanlar", "original": "orijinal/ilk", "inhabitants": "sakinler/yaşayanlar", "across": "boyunca", "mountains": "dağlar", "deserts": "çöller", "long": "uzun", "history": "tarih", "goes back": "geriye gider", "time": "zaman", "Ancient": "Antik/Eski", "famous": "ünlü", "beautiful": "güzel", "silver": "gümüş", "jewelry": "takı/mücevher", "colorful": "renkli", "carpets": "halılar", "unique": "benzersiz", "music": "müzik", "lived": "yaşadılar", "massive": "muazzam", "mud-brick": "kerpiç", "castles": "kaleler", "Even": "hatta", "today": "bugün", "many": "birçok", "families": "aileler", "follow": "takip etmek", "traditions": "gelenekler", "ancestors": "atalar" },
    questions: [ {q:"Do the Berbers call themselves the Amazigh?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they the original inhabitants of North Africa?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their history go back to Ancient Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for gold jewelry?", a_en:"No", a_tr:"Hayır"}, {q:"Are Kasbahs massive mud-brick castles?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many Berber families still live in the mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they follow the traditions of their ancestors?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_Copts.mp3"] = [{
    text: `The Copts are the indigenous Christians of Egypt and are the direct descendants of the ancient people who lived during the time of the Pharaohs. The word "Copt" comes from the ancient Greek word for "Egyptian." They have their own language, Coptic, which is the final stage of the ancient Egyptian language. It is still used in their church ceremonies today. They have kept their unique traditions and Christian faith alive for nearly 2,000 years. They are famous for "Coptic Art," which uses bright colors and simple shapes. Many Copts have a small cross tattooed on their wrist as a symbol of their identity.`,
    dict: { "indigenous": "yerli", "direct": "doğrudan", "descendants": "soyundan gelenler", "ancient": "antik/eski", "lived": "yaşadılar", "during": "sırasında", "time": "zaman", "word": "kelime", "comes": "gelir", "own": "kendi", "language": "dil", "final": "son", "stage": "aşama", "still": "hala", "used": "kullanılır", "church": "kilise", "ceremonies": "törenler", "today": "bugün", "kept": "tuttu/korudu", "unique": "benzersiz", "traditions": "gelenekler", "faith": "inanç", "alive": "canlı", "nearly": "neredeyse", "years": "yıllar", "famous": "ünlü", "Art": "Sanat", "uses": "kullanır", "bright": "parlak", "colors": "renkler", "simple": "basit", "shapes": "şekiller", "small": "küçük", "cross": "haç", "tattooed": "dövme yapılmış", "wrist": "bilek", "symbol": "sembol", "identity": "kimlik" },
    questions: [ {q:"Are the Copts the indigenous Christians of Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they descendants of the ancient Egyptians?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Coptic language still used in church ceremonies?", a_en:"Yes", a_tr:"Evet"}, {q:"Have they kept their faith alive for 2,000 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Coptic Art use dark colors and complex shapes?", a_en:"No", a_tr:"Hayır"}, {q:"Do many Copts have a cross tattooed on their wrist?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the tattoo a symbol of their identity?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_Dogon.mp3"] = [{
    text: `The Dogon people live in a spectacular place called the Bandiagara Escarpment in Mali. They built their homes into the sides of giant cliffs to protect themselves. The Dogon are famous because they have a complex knowledge of astronomy and stars that they have known for hundreds of years. They are also known for their wooden masks and dances. Every 60 years, they hold a massive festival called the "Sigui" to celebrate the changing of the generations. Their culture is full of mystery, and they remain one of the most interesting groups in Africa.`,
    dict: { "spectacular": "muhteşem", "place": "yer", "called": "adlandırılan", "built": "inşa etti", "homes": "evler", "sides": "yanlar", "giant": "dev", "cliffs": "uçurumlar", "protect": "korumak", "themselves": "kendilerini", "famous": "ünlü", "because": "çünkü", "complex": "karmaşık", "knowledge": "bilgi", "astronomy": "astronomi", "stars": "yıldızlar", "known": "bilinen", "hundreds": "yüzlerce", "years": "yıllar", "also": "ayrıca", "wooden": "ahşap", "masks": "maskeler", "dances": "danslar", "Every": "her", "hold": "düzenler", "massive": "muazzam", "festival": "festival", "celebrate": "kutlamak", "changing": "değişim", "generations": "nesiller", "culture": "kültür", "full": "dolu", "mystery": "gizem", "remain": "kalır/olmaya devam eder", "most": "en", "interesting": "ilginç", "groups": "gruplar" },
    questions: [ {q:"Do the Dogon live in Mali?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they build their homes into the sides of giant cliffs?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have complex knowledge of astronomy?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they known for making plastic toys?", a_en:"No", a_tr:"Hayır"}, {q:"Do they hold the Sigui festival every 60 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the festival celebrate the changing of generations?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their culture full of mystery?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_Gauchos.mp3"] = [{
    text: `Gauchos are the legendary "cowboys" of the South American plains. They are famous for being expert horsemen who lived a nomadic life herding cattle. A typical Gaucho wears a wide hat, a poncho, and carries a special knife. They are symbols of freedom and bravery in Argentina and Uruguay. Gauchos are famous for their music and for "Asado," which is a traditional way of roasting meat over a large fire. Although the nomadic life has mostly ended, their culture is still an important part of national pride.`,
    dict: { "legendary": "efsanevi", "plains": "ovalar", "famous": "ünlü", "expert": "uzman", "horsemen": "atlılar", "lived": "yaşadılar", "nomadic": "göçebe", "life": "hayat", "herding": "sürü gütme", "cattle": "sığır", "typical": "tipik", "wears": "giyer", "wide": "geniş", "hat": "şapka", "carries": "taşır", "special": "özel", "knife": "bıçak", "symbols": "semboller", "freedom": "özgürlük", "bravery": "cesaret", "music": "müzik", "traditional": "geleneksel", "way": "yol/yöntem", "roasting": "kızartma", "meat": "et", "over": "üzerinde", "large": "büyük", "fire": "ateş", "Although": "rağmen", "mostly": "çoğunlukla", "ended": "bitti", "culture": "kültür", "still": "hala", "important": "önemli", "part": "parça", "national": "ulusal", "pride": "gurur" },
    questions: [ {q:"Are Gauchos the legendary cowboys of South America?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for being expert horsemen?", a_en:"Yes", a_tr:"Evet"}, {q:"Does a typical Gaucho wear a wide hat and a poncho?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they symbols of fear and weakness?", a_en:"No", a_tr:"Hayır"}, {q:"Is 'Asado' a traditional way of roasting meat?", a_en:"Yes", a_tr:"Evet"}, {q:"Has the nomadic life mostly ended?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their culture still an important part of national pride?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_Hadza.mp3"] = [{
    text: `The Hadza are one of the last true hunter-gatherer groups left on Earth. They live near Lake Eyasi in Tanzania and have lived the same way for tens of thousands of years. They do not grow food or keep animals; instead, they hunt wild animals with bows and find honey and berries in the bush. The Hadza speak a unique "click" language. They have no leaders and no private property; everyone shares everything. They live in perfect balance with nature. Scientists study them to understand how humans lived a long time ago.`,
    dict: { "last": "son", "true": "gerçek", "hunter-gatherer": "avcı-toplayıcı", "groups
