const lessonData = {};

lessonData["01_Ainu.mp3"] = [{
    text: `The Ainu are the indigenous people of northern Japan, specifically the island of Hokkaido. For a long time, their culture was a secret. They have a unique language that is not related to Japanese. The Ainu believe that spirits, called "kamuy," live in everything in nature, especially in bears and owls. Historically, Ainu men grew thick beards and women had traditional tattoos around their mouths. They were expert hunters and fishermen. Today, the Ainu work hard to keep their language and traditions alive through music and festivals. They are a symbol of the diverse history of the Japanese islands.`,
    dict: { "indigenous": "yerli", "northern": "kuzey", "specifically": "özellikle", "island": "ada", "long time": "uzun zaman", "culture": "kültür", "secret": "sır", "unique": "eşsiz/benzersiz", "language": "dil", "related": "bağlantılı/akraba", "believe": "inanmak", "spirits": "ruhlar", "called": "adlandırılan", "live": "yaşamak", "everything": "her şey", "nature": "doğa", "especially": "özellikle", "bears": "ayılar", "owls": "baykuşlar", "historically": "tarihsel olarak", "men": "erkekler", "grew": "büyüttü/uzattı", "thick": "kalın/gür", "beards": "sakallar", "women": "kadınlar", "traditional": "geleneksel", "tattoos": "dövmeler", "around": "etrafında", "mouths": "ağızlar", "expert": "uzman", "hunters": "avcılar", "fishermen": "balıkçılar", "today": "bugün", "work": "çalışmak", "hard": "sıkı/zor", "keep": "tutmak/korumak", "traditions": "gelenekler", "alive": "canlı", "through": "aracılığıyla", "music": "müzik", "festivals": "festivaller", "symbol": "sembol", "diverse": "çeşitli", "history": "tarih", "islands": "adalar" },
    questions: [ {q:"Are the Ainu the indigenous people of northern Japan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was their culture a secret for a long time?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their language have relation to Japanese?", a_en:"No", a_tr:"Hayır"}, {q:"Do they believe spirits live in bears and owls?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Ainu men grow thick beards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did women have tattoos around their eyes?", a_en:"No", a_tr:"Hayır"}, {q:"Do they keep their traditions alive through festivals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_Badjao.mp3"] = [{
    text: `The Badjao are known as "Sea Nomads" because they spend almost their entire lives on the water. They live in houseboats or houses built on stilts over the ocean in the Philippines and Malaysia. Many Badjao are born and live at sea without staying on land for long. Because they dive for fish every day, their bodies have changed; they can see clearly underwater and hold their breath for several minutes. They are some of the best divers in the world. They are peaceful people who move across the ocean following the fish and the seasons.`,
    dict: { "known as": "olarak bilinen", "Sea": "Deniz", "Nomads": "Göçebeler", "because": "çünkü", "spend": "harcarlar/geçirirler", "almost": "neredeyse", "entire": "tüm/bütün", "lives": "hayatlar", "water": "su", "houseboats": "yüzen evler", "built": "inşa edilmiş", "stilts": "kazıklar", "over": "üzerinde", "ocean": "okyanus", "born": "doğmuş", "sea": "deniz", "without": "olmadan", "staying": "kalma", "land": "kara", "long": "uzun süre", "dive": "dalarlar", "fish": "balık", "every day": "her gün", "bodies": "vücutlar", "changed": "değişti", "see": "görmek", "clearly": "açıkça/net", "underwater": "sualtı", "hold": "tutmak", "breath": "nefes", "several": "birkaç", "minutes": "dakikalar", "best": "en iyi", "divers": "dalgıçlar", "world": "dünya", "peaceful": "barışçıl/huzurlu", "people": "insanlar", "move": "hareket etmek", "across": "boyunca", "following": "takip eden", "seasons": "mevsimler" },
    questions: [ {q:"Are the Badjao known as Sea Nomads?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they spend their entire lives on the water?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in houses built on stilts?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make long stays on land?", a_en:"No", a_tr:"Hayır"}, {q:"Can they see clearly underwater?", a_en:"Yes", a_tr:"Evet"}, {q:"Can they hold their breath for only five seconds?", a_en:"No", a_tr:"Hayır"}, {q:"Are they some of the best divers in the world?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_Basque.mp3"] = [{
    text: `The Basque people live in a region between Spain and France. They are a mystery in Europe because their language, "Euskara," is not related to any other language on Earth. No one knows exactly where they came from. They are proud of their identity and have unique sports and music. They are famous for being excellent sailors and for their delicious "pintxos" (small snacks). The Basque culture is very strong, and they have kept their traditions alive for thousands of years despite being surrounded by much larger nations.`,
    dict: { "region": "bölge", "between": "arasında", "mystery": "gizem", "Europe": "Avrupa", "language": "dil", "related": "bağlantılı/akraba", "other": "diğer", "Earth": "Dünya", "knows": "bilir", "exactly": "kesinlikle/tam olarak", "came from": "geldi", "proud": "gururlu", "identity": "kimlik", "unique": "benzersiz", "sports": "sporlar", "music": "müzik", "famous": "ünlü", "excellent": "mükemmel", "sailors": "denizciler", "delicious": "lezzetli", "small": "küçük", "snacks": "atıştırmalıklar", "culture": "kültür", "strong": "güçlü", "kept": "tuttu/korudu", "traditions": "gelenekler", "alive": "canlı", "thousands": "binlerce", "years": "yıllar", "despite": "rağmen", "surrounded": "kuşatılmış", "much": "çok", "larger": "daha büyük", "nations": "uluslar/milletler" },
    questions: [ {q:"Do the Basque people live between Spain and France?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their language related to no other language on Earth?", a_en:"Yes", a_tr:"Evet"}, {q:"Does nobody know exactly where they came from?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they proud of their identity?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for being excellent sailors?", a_en:"Yes", a_tr:"Evet"}, {q:"Are 'pintxos' large, heavy meals?", a_en:"No", a_tr:"Hayır"}, {q:"Have they kept their traditions alive for thousands of years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Bedouin.mp3"] = [{
    text: `The Bedouin are the legendary nomadic people of the Arabian and Saharan deserts. The word "Bedouin" means "desert dweller." For centuries, they have traveled across the dry sands with their camels, goats, and sheep. They live in large black tents made of goat hair. The Bedouin are famous for their incredible hospitality; if a stranger comes to their tent, they will give them food and water for three days. Although many now live in cities, they still feel a deep connection to the desert and their traditional tribal laws.`,
    dict: { "legendary": "efsanevi", "nomadic": "göçebe", "deserts": "çöller", "word": "kelime", "means": "anlamına gelir", "dweller": "sakin/yaşayan", "centuries": "yüzyıllar", "traveled": "seyahat ettiler", "across": "boyunca", "dry": "kuru", "sands": "kumlar", "camels": "develer", "goats": "keçiler", "sheep": "koyunlar", "large": "büyük", "black": "siyah", "tents": "çadırlar", "made of": "yapılmış", "hair": "kıl/saç", "famous": "ünlü", "incredible": "inanılmaz", "hospitality": "misafirperverlik", "stranger": "yabancı", "comes": "gelir", "food": "yiyecek", "water": "su", "days": "günler", "Although": "rağmen", "many": "birçoğu", "now": "şimdi", "cities": "şehirler", "still": "hala", "feel": "hisseder", "deep": "derin", "connection": "bağlantı", "traditional": "geleneksel", "tribal": "kabile", "laws": "yasalar" },
    questions: [ {q:"Are the Bedouin nomadic people of the desert?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the word Bedouin mean 'desert dweller'?", a_en:"Yes", a_tr:"Evet"}, {q:"Have they traveled with camels and goats for centuries?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in blue tents made of cotton?", a_en:"No", a_tr:"Hayır"}, {q:"Are they famous for incredible hospitality?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they give strangers food and water for three days?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many still feel a deep connection to the desert?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_Berbers.mp3"] = [{
    text: `The Berbers, who call themselves the "Amazigh" (meaning free people), are the original inhabitants of North Africa. They live across the mountains and deserts of Morocco, Algeria, and Tunisia. They have a long history that goes back to the time of the Ancient Egyptians. The Berbers are famous for their beautiful silver jewelry, colorful carpets, and unique music. They lived in "Kasbahs," which are massive mud-brick castles. Even today, many Berber families live in the mountains and follow the traditions of their ancestors.`,
    dict: { "themselves": "kendilerini", "meaning": "anlamına gelen", "free": "özgür", "people": "insanlar", "original": "orijinal/ilk", "inhabitants": "sakinler/yaşayanlar", "across": "boyunca", "mountains": "dağlar", "deserts": "çöller", "long": "uzun", "history": "tarih", "goes back": "geriye gider", "time": "zaman", "Ancient": "Antik/Eski", "famous": "ünlü", "beautiful": "güzel", "silver": "gümüş", "jewelry": "takı/mücevher", "colorful": "renkli", "carpets": "halılar", "unique": "benzersiz", "music": "müzik", "lived": "yaşadılar", "massive": "muazzam", "mud-brick": "kerpiç", "castles": "kaleler", "Even": "hatta", "today": "bugün", "many": "birçok", "families": "aileler", "follow": "takip etmek", "traditions": "gelenekler", "ancestors": "atalar" },
    questions: [ {q:"Do the Berbers call themselves the Amazigh?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they the original inhabitants of North Africa?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their history go back to Ancient Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for gold jewelry?", a_en:"No", a_tr:"Hayır"}, {q:"Are Kasbahs massive mud-brick castles?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many Berber families still live in the mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they follow the traditions of their ancestors?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_Copts.mp3"] = [{
    text: `The Copts are the indigenous Christians of Egypt and are the direct descendants of the ancient people who lived during the time of the Pharaohs. The word "Copt" comes from the ancient Greek word for "Egyptian." They have their own language, Coptic, which is the final stage of the ancient Egyptian language. It is still used in their church ceremonies today. They have kept their unique traditions and Christian faith alive for nearly 2,000 years. They are famous for "Coptic Art," which uses bright colors and simple shapes. Many Copts have a small cross tattooed on their wrist as a symbol of their identity.`,
    dict: { "indigenous": "yerli", "direct": "doğrudan", "descendants": "soyundan gelenler", "ancient": "antik/eski", "lived": "yaşadılar", "during": "sırasında", "time": "zaman", "word": "kelime", "comes": "gelir", "own": "kendi", "language": "dil", "final": "son", "stage": "aşama", "still": "hala", "used": "kullanılır", "church": "kilise", "ceremonies": "törenler", "today": "bugün", "kept": "tuttu/korudu", "unique": "benzersiz", "traditions": "gelenekler", "faith": "inanç", "alive": "canlı", "nearly": "neredeyse", "years": "yıllar", "famous": "ünlü", "Art": "Sanat", "uses": "kullanır", "bright": "parlak", "colors": "renkler", "simple": "basit", "shapes": "şekiller", "small": "küçük", "cross": "haç", "tattooed": "dövme yapılmış", "wrist": "bilek", "symbol": "sembol", "identity": "kimlik" },
    questions: [ {q:"Are the Copts the indigenous Christians of Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they descendants of the ancient Egyptians?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Coptic language still used in church ceremonies?", a_en:"Yes", a_tr:"Evet"}, {q:"Have they kept their faith alive for 2,000 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Coptic Art use dark colors and complex shapes?", a_en:"No", a_tr:"Hayır"}, {q:"Do many Copts have a cross tattooed on their wrist?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the tattoo a symbol of their identity?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_Dogon.mp3"] = [{
    text: `The Dogon people live in a spectacular place called the Bandiagara Escarpment in Mali. They built their homes into the sides of giant cliffs to protect themselves. The Dogon are famous because they have a complex knowledge of astronomy and stars that they have known for hundreds of years. They are also known for their wooden masks and dances. Every 60 years, they hold a massive festival called the "Sigui" to celebrate the changing of the generations. Their culture is full of mystery, and they remain one of the most interesting groups in Africa.`,
    dict: { "spectacular": "muhteşem", "place": "yer", "called": "adlandırılan", "built": "inşa etti", "homes": "evler", "sides": "yanlar", "giant": "dev", "cliffs": "uçurumlar", "protect": "korumak", "themselves": "kendilerini", "famous": "ünlü", "because": "çünkü", "complex": "karmaşık", "knowledge": "bilgi", "astronomy": "astronomi", "stars": "yıldızlar", "known": "bilinen", "hundreds": "yüzlerce", "years": "yıllar", "also": "ayrıca", "wooden": "ahşap", "masks": "maskeler", "dances": "danslar", "Every": "her", "hold": "düzenler", "massive": "muazzam", "festival": "festival", "celebrate": "kutlamak", "changing": "değişim", "generations": "nesiller", "culture": "kültür", "full": "dolu", "mystery": "gizem", "remain": "kalır/olmaya devam eder", "most": "en", "interesting": "ilginç", "groups": "gruplar" },
    questions: [ {q:"Do the Dogon live in Mali?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they build their homes into the sides of giant cliffs?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have complex knowledge of astronomy?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they known for making plastic toys?", a_en:"No", a_tr:"Hayır"}, {q:"Do they hold the Sigui festival every 60 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the festival celebrate the changing of generations?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their culture full of mystery?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_Gauchos.mp3"] = [{
    text: `Gauchos are the legendary "cowboys" of the South American plains. They are famous for being expert horsemen who lived a nomadic life herding cattle. A typical Gaucho wears a wide hat, a poncho, and carries a special knife. They are symbols of freedom and bravery in Argentina and Uruguay. Gauchos are famous for their music and for "Asado," which is a traditional way of roasting meat over a large fire. Although the nomadic life has mostly ended, their culture is still an important part of national pride.`,
    dict: { "legendary": "efsanevi", "plains": "ovalar", "famous": "ünlü", "expert": "uzman", "horsemen": "atlılar", "lived": "yaşadılar", "nomadic": "göçebe", "life": "hayat", "herding": "sürü gütme", "cattle": "sığır", "typical": "tipik", "wears": "giyer", "wide": "geniş", "hat": "şapka", "carries": "taşır", "special": "özel", "knife": "bıçak", "symbols": "semboller", "freedom": "özgürlük", "bravery": "cesaret", "music": "müzik", "traditional": "geleneksel", "way": "yol/yöntem", "roasting": "kızartma", "meat": "et", "over": "üzerinde", "large": "büyük", "fire": "ateş", "Although": "rağmen", "mostly": "çoğunlukla", "ended": "bitti", "culture": "kültür", "still": "hala", "important": "önemli", "part": "parça", "national": "ulusal", "pride": "gurur" },
    questions: [ {q:"Are Gauchos the legendary cowboys of South America?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for being expert horsemen?", a_en:"Yes", a_tr:"Evet"}, {q:"Does a typical Gaucho wear a wide hat and a poncho?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they symbols of fear and weakness?", a_en:"No", a_tr:"Hayır"}, {q:"Is 'Asado' a traditional way of roasting meat?", a_en:"Yes", a_tr:"Evet"}, {q:"Has the nomadic life mostly ended?", a_en:"Yes", a_tr:"Evet"}, {q:"Is their culture still an important part of national pride?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_Hadza.mp3"] = [{
    text: `The Hadza are one of the last true hunter-gatherer groups left on Earth. They live near Lake Eyasi in Tanzania and have lived the same way for tens of thousands of years. They do not grow food or keep animals; instead, they hunt wild animals with bows and find honey and berries in the bush. The Hadza speak a unique "click" language. They have no leaders and no private property; everyone shares everything. They live in perfect balance with nature. Scientists study them to understand how humans lived a long time ago.`,
    dict: { "last": "son", "true": "gerçek", "hunter-gatherer": "avcı-toplayıcı", "groups": "gruplar", "left": "kalan", "Earth": "Dünya", "near": "yakın", "Lake": "Göl", "lived": "yaşadı", "same": "aynı", "way": "yol/şekil", "thousands": "binlerce", "years": "yıllar", "grow": "yetiştirmek", "food": "yiyecek", "keep": "tutmak/beslemek", "animals": "hayvanlar", "instead": "bunun yerine", "hunt": "avlanmak", "wild": "vahşi", "bows": "yaylar", "find": "bulmak", "honey": "bal", "berries": "meyveler", "bush": "çalılık", "speak": "konuşmak", "unique": "benzersiz", "language": "dil", "leaders": "liderler", "private": "özel", "property": "mülkiyet", "shares": "paylaşır", "everything": "her şey", "perfect": "mükemmel", "balance": "denge", "nature": "doğa", "Scientists": "Bilim insanları", "study": "inceler", "understand": "anlamak", "humans": "insanlar", "ago": "önce" },
    questions: [ {q:"Are the Hadza a hunter-gatherer group?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they grow no food and keep no animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they hunt wild animals with bows?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they speak a unique click language?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have strict leaders and private property?", a_en:"No", a_tr:"Hayır"}, {q:"Does everyone share everything?", a_en:"Yes", a_tr:"Evet"}, {q:"Do scientists study them to understand early humans?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_Himba.mp3"] = [{
    text: `The Himba people live in the dry Kunene region of Namibia. They are famous because the women cover their skin and hair with a mixture called "otjize," made of red ochre and animal fat. This gives their skin a red color and protects them from the hot sun. The Himba are semi-nomadic farmers who raise cattle and goats. They live in small huts made of mud and wood. The center of the village is the "holy fire," which must never go out because it connects the living with their ancestors.`,
    dict: { "dry": "kuru", "region": "bölge", "famous": "ünlü", "women": "kadınlar", "cover": "kaplar", "skin": "deri/cilt", "hair": "saç", "mixture": "karışım", "called": "adlandırılan", "made of": "yapılmış", "red": "kırmızı", "animal": "hayvan", "fat": "yağ", "gives": "verir", "color": "renk", "protects": "korur", "hot": "sıcak", "sun": "güneş", "semi-nomadic": "yarı göçebe", "farmers": "çiftçiler", "raise": "yetiştirmek/beslemek", "cattle": "sığır", "goats": "keçiler", "live": "yaşarlar", "small": "küçük", "huts": "kulübeler", "mud": "çamur", "wood": "ahşap/odun", "center": "merkez", "village": "köy", "holy": "kutsal", "fire": "ateş", "never": "asla", "go out": "sönmek", "because": "çünkü", "connects": "bağlar", "living": "yaşayanlar", "ancestors": "atalar" },
    questions: [ {q:"Do the Himba people live in Namibia?", a_en:"Yes", a_tr:"Evet"}, {q:"Do women cover their skin with a mixture called otjize?", a_en:"Yes", a_tr:"Evet"}, {q:"Does otjize give their skin a blue color?", a_en:"No", a_tr:"Hayır"}, {q:"Does the mixture protect them from the hot sun?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the Himba semi-nomadic farmers?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in big concrete houses?", a_en:"No", a_tr:"Hayır"}, {q:"Must the holy fire never go out?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_HuliWigmen.mp3"] = [{
    text: `The Huli people live in the central mountains of Papua New Guinea. They are called "Wigmen" because the men grow their own hair for many months to create massive, beautiful wigs. They decorate these wigs with bird feathers and flowers. For special ceremonies, they paint their faces bright yellow and red. The Huli are proud warriors and have complex rules for their society. Men and women often live in separate houses. Their dances, where they jump and imitate the movements of birds, are a spectacular sight.`,
    dict: { "central": "merkez/orta", "mountains": "dağlar", "called": "adlandırılan", "grow": "uzatmak/büyütmek", "own": "kendi", "hair": "saç", "many": "birçok", "months": "aylar", "create": "yaratmak/yapmak", "massive": "muazzam", "beautiful": "güzel", "wigs": "peruklar", "decorate": "süslemek", "feathers": "tüyler", "flowers": "çiçekler", "special": "özel", "ceremonies": "törelner", "paint": "boyamak", "faces": "yüzler", "bright": "parlak", "yellow": "sarı", "red": "kırmızı", "proud": "gururlu", "warriors": "savaşçılar", "complex": "karmaşık", "rules": "kurallar", "society": "toplum", "often": "sık sık", "separate": "ayrı", "houses": "evler", "dances": "danslar", "jump": "zıplamak", "imitate": "taklit etmek", "movements": "hareketler", "birds": "kuşlar", "spectacular": "muhteşem", "sight": "manzara/görünüm" },
    questions: [ {q:"Do the Huli live in Papua New Guinea?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the men grow their hair to create wigs?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they decorate wigs with feathers and flowers?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they paint their faces blue and green?", a_en:"No", a_tr:"Hayır"}, {q:"Are the Huli proud warriors with complex rules?", a_en:"Yes", a_tr:"Evet"}, {q:"Do men and women always live in the same house?", a_en:"No", a_tr:"Hayır"}, {q:"Do their dances imitate the movements of birds?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_Kalash.mp3"] = [{
    text: `The Kalash are a unique group living in the high mountains of Pakistan near Afghanistan. They are different from everyone else in the region because they have their own ancient religion and festivals. Many Kalash people have fair skin and light eyes. The women wear bright, colorful black dresses with beautiful embroidery and orange headdresses. They love music, dancing, and making their own wine. The Kalash are peaceful people who have managed to protect their unique culture for over 2,000 years in the middle of a different world.`,
    dict: { "unique": "benzersiz", "group": "grup", "living": "yaşayan", "high": "yüksek", "mountains": "dağlar", "near": "yakın", "different": "farklı", "everyone": "herkes", "else": "başka", "region": "bölge", "because": "çünkü", "own": "kendi", "ancient": "antik/eski", "religion": "din", "festivals": "festivaller", "many": "birçoğu", "fair": "açık (renk)", "skin": "ten/cilt", "light": "açık (renk)/ışık", "eyes": "gözler", "women": "kadınlar", "wear": "giyer", "bright": "parlak", "colorful": "renkli", "black": "siyah", "dresses": "elbiseler", "beautiful": "güzel", "embroidery": "nakış", "orange": "turuncu", "headdresses": "başlıklar", "love": "sever", "music": "müzik", "dancing": "dans etme", "making": "yapma", "wine": "şarap", "peaceful": "barışçıl/huzurlu", "managed": "başardı", "protect": "korumak", "culture": "kültür", "over": "üzerinde/fazla", "years": "yıllar", "middle": "orta", "world": "dünya" },
    questions: [ {q:"Do the Kalash live in the mountains of Pakistan?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have their own ancient religion?", a_en:"Yes", a_tr:"Evet"}, {q:"Do many Kalash people have fair skin and light eyes?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the women wear plain white dresses?", a_en:"No", a_tr:"Hayır"}, {q:"Do they love making their own wine?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the Kalash aggressive people?", a_en:"No", a_tr:"Hayır"}, {q:"Have they protected their culture for over 2,000 years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_KazakhNomads.mp3"] = [{
    text: `The Kazakh nomads live in the vast grasslands of Central Asia and Mongolia. They are famous for living in "yurts," which are large tents that can be moved easily. The most spectacular tradition of the Kazakh people is eagle hunting. They train giant golden eagles to sit on their arms and hunt small animals. This tradition is thousands of years old and is passed from father to son. Kazakh people are also famous for their hospitality and their skill at riding horses. They keep the spirit of the ancient Silk Road alive.`,
    dict: { "nomads": "göçebeler", "vast": "geniş", "grasslands": "otlaklar/bozkırlar", "Central": "Orta", "famous": "ünlü", "living": "yaşamak", "yurts": "yurtlar (çadır)", "large": "büyük", "tents": "çadırlar", "moved": "taşınmış", "easily": "kolayca", "most": "en", "spectacular": "muhteşem", "tradition": "gelenek", "eagle": "kartal", "hunting": "avcılık", "train": "eğitmek", "giant": "dev", "golden": "altın", "sit": "oturmak", "arms": "kollar", "hunt": "avlamak", "small": "küçük", "animals": "hayvanlar", "thousands": "binlerce", "years": "yıllar", "old": "eski", "passed": "aktarılır/geçer", "father": "baba", "son": "oğul", "also": "ayrıca", "hospitality": "misafirperverlik", "skill": "yetenek/beceri", "riding": "binme", "horses": "atlar", "keep": "tutmak/korumak", "spirit": "ruh", "ancient": "antik", "Silk Road": "İpek Yolu", "alive": "canlı" },
    questions: [ {q:"Do the Kazakh nomads live in the grasslands of Central Asia?", a_en:"Yes", a_tr:"Evet"}, {q:"Are 'yurts' large tents that can be moved easily?", a_en:"Yes", a_tr:"Evet"}, {q:"Is eagle hunting a spectacular tradition?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they train giant golden eagles?", a_en:"Yes", a_tr:"Evet"}, {q:"Is this tradition only ten years old?", a_en:"No", a_tr:"Hayır"}, {q:"Are they famous for their skill at riding horses?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they keep the spirit of the Silk Road alive?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_Khasi.mp3"] = [{
    text: `The Khasi people live in the rainy hills of Meghalaya in Northeast India. They are famous because they have a "matrilineal" society. This means women are the leaders of the family. Children take their mother’s last name, and when a woman gets married, her husband often moves into her family's house. The youngest daughter inherits all the property. The Khasi are also famous for building "living root bridges" by training the roots of trees to grow across rivers. These bridges are hundreds of years old.`,
    dict: { "rainy": "yağmurlu", "hills": "tepeler", "Northeast": "Kuzeydoğu", "famous": "ünlü", "because": "çünkü", "matrilineal": "anaerkil", "society": "toplum", "means": "anlamına gelir", "women": "kadınlar", "leaders": "liderler", "family": "aile", "Children": "Çocuklar", "take": "alır", "mother's": "annenin", "last name": "soyadı", "married": "evli", "husband": "koca", "often": "sık sık", "moves": "taşınır", "house": "ev", "youngest": "en genç", "daughter": "kız çocuk", "inherits": "miras alır", "all": "tüm", "property": "mülk/mal", "also": "ayrıca", "building": "inşa etme", "living": "yaşayan", "root": "kök", "bridges": "köprüler", "training": "eğitmek/şekil vermek", "roots": "kökler", "trees": "ağaçlar", "grow": "büyümek", "across": "karşısına", "rivers": "nehirler", "hundreds": "yüzlerce", "years": "yıllar", "old": "eski" },
    questions: [ {q:"Do the Khasi people live in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a matrilineal society?", a_en:"Yes", a_tr:"Evet"}, {q:"Do children take their father's last name?", a_en:"No", a_tr:"Hayır"}, {q:"Does the husband often move into the wife's family house?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the youngest daughter inherit all the property?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they build 'living root bridges'?", a_en:"Yes", a_tr:"Evet"}, {q:"Are these bridges built using steel and concrete?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["15_LappsSami.mp3"] = [{
    text: `The Sami, also known as the Lapps, are the indigenous people of the Arctic parts of Norway, Sweden, Finland, and Russia. They are famous for their ancient tradition of reindeer herding. For centuries, they followed the reindeer across the snow and lived in tents called "lavvu." They wear bright blue and red clothes called "Gakti." The Sami have a unique way of singing called "Joik," which is one of the oldest musical traditions in Europe. Today, they use snowmobiles, but they still keep their deep connection to the frozen land and the Northern Lights.`,
    dict: { "known": "bilinen", "indigenous": "yerli", "Arctic": "Kuzey Kutbu", "parts": "kısımlar", "famous": "ünlü", "ancient": "antik/eski", "tradition": "gelenek", "reindeer": "ren geyiği", "herding": "sürü gütme", "centuries": "yüzyıllar", "followed": "takip ettiler", "across": "boyunca", "snow": "kar", "lived": "yaşadılar", "tents": "çadırlar", "called": "adlandırılan", "wear": "giyerler", "bright": "parlak", "blue": "mavi", "red": "kırmızı", "clothes": "kıyafetler", "unique": "benzersiz", "way": "yol/tarz", "singing": "şarkı söyleme", "oldest": "en eski", "musical": "müzikal", "traditions": "gelenekler", "Europe": "Avrupa", "Today": "bugün", "use": "kullanırlar", "snowmobiles": "kar motosikletleri", "still": "hala", "keep": "tutmak/korumak", "deep": "derin", "connection": "bağlantı", "frozen": "donmuş", "land": "toprak", "Northern Lights": "Kuzey Işıkları" },
    questions: [ {q:"Are the Sami the indigenous people of the Arctic?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for reindeer herding?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they live in tents called 'lavvu'?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they wear bright blue and red clothes?", a_en:"Yes", a_tr:"Evet"}, {q:"Is 'Joik' a very modern type of dance?", a_en:"No", a_tr:"Hayır"}, {q:"Do they use snowmobiles today?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a deep connection to the Northern Lights?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_Maasai.mp3"] = [{
    text: `The Maasai are a famous indigenous group in Africa. They live in the plains of Kenya and Tanzania. The Maasai are iconic for their bright red robes, called "shuka," and their bead jewelry. They are a warrior culture that measures wealth by the number of cattle and children a man has. One of their most famous traditions is the "Adumu" dance, where young warriors compete to see who can jump the highest. The Maasai live in small villages called "Manyattas" and continue to live their traditional life among the lions and elephants.`,
    dict: { "famous": "ünlü", "indigenous": "yerli", "group": "grup", "live": "yaşarlar", "plains": "ovalar", "iconic": "ikonik", "bright": "parlak", "red": "kırmızı", "robes": "cübbeler", "called": "adlandırılan", "bead": "boncuk", "jewelry": "takı", "warrior": "savaşçı", "culture": "kültür", "measures": "ölçer", "wealth": "zenginlik", "number": "sayı", "cattle": "sığır", "children": "çocuklar", "man": "adam", "has": "sahiptir", "One": "biri", "most": "en", "traditions": "gelenekler", "dance": "dans", "young": "genç", "compete": "rekabet etmek", "see": "görmek", "jump": "zıplamak", "highest": "en yüksek", "small": "küçük", "villages": "köyler", "continue": "devam etmek", "traditional": "geleneksel", "life": "hayat", "among": "arasında", "lions": "aslanlar", "elephants": "filler" },
    questions: [ {q:"Are the Maasai a famous group in Africa?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they wear bright blue robes?", a_en:"No", a_tr:"Hayır"}, {q:"Is their wealth measured by the number of cattle?", a_en:"Yes", a_tr:"Evet"}, {q:"Do young warriors compete by jumping in the Adumu dance?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live in big, modern cities?", a_en:"No", a_tr:"Hayır"}, {q:"Are their small villages called Manyattas?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live among lions and elephants?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_Quechua.mp3"] = [{
    text: `The Quechua people are the direct descendants of the famous Inca Empire. They live high in the Andes mountains of Peru, Bolivia, and Ecuador. They still speak the Quechua language. They are famous for their beautiful, colorful ponchos and hats made of llama and alpaca wool. The Quechua are expert farmers who grow hundreds of types of potatoes on steep mountain slopes. They have a deep respect for "Pachamama," or Mother Earth. Many follow ancient traditions like performing ceremonies at sites like Machu Picchu.`,
    dict: { "direct": "doğrudan", "descendants": "soyundan gelenler", "famous": "ünlü", "Empire": "İmparatorluk", "live": "yaşarlar", "high": "yüksek", "mountains": "dağlar", "still": "hala", "speak": "konuşurlar", "language": "dil", "beautiful": "güzel", "colorful": "renkli", "hats": "şapkalar", "made of": "yapılmış", "wool": "yün", "expert": "uzman", "farmers": "çiftçiler", "grow": "yetiştirirler", "hundreds": "yüzlerce", "types": "türler", "potatoes": "patatesler", "steep": "dik", "slopes": "yamaçlar", "deep": "derin", "respect": "saygı", "Mother": "Anne", "Earth": "Dünya/Toprak", "Many": "birçoğu", "follow": "takip eder", "ancient": "antik/eski", "traditions": "gelenekler", "performing": "gerçekleştirme", "ceremonies": "törenler", "sites": "alanlar/yerler" },
    questions: [ {q:"Are the Quechua descendants of the Inca Empire?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they live high in the Andes mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they make clothes from llama and alpaca wool?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they bad at farming?", a_en:"No", a_tr:"Hayır"}, {q:"Do they grow hundreds of types of potatoes?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a deep respect for Mother Earth?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they perform ceremonies at Machu Picchu?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_Sherpa.mp3"] = [{
    text: `The Sherpa are a group who live in the highest mountains of the Himalayas. Because they live at high altitudes, their bodies are very strong and can breathe easily in thin air. This has made them famous as the best mountain climbers on Earth. Without the help of Sherpas, it would be almost impossible for foreign climbers to reach the top of Mount Everest. They are religious people who follow Tibetan Buddhism. The word "Sherpa" has become a symbol of strength, bravery, and friendship in the world of adventure.`,
    dict: { "group": "grup", "live": "yaşarlar", "highest": "en yüksek", "mountains": "dağlar", "Because": "çünkü", "altitudes": "rakımlar/yükseklikler", "bodies": "vücutlar", "strong": "güçlü", "breathe": "nefes almak", "easily": "kolayca", "thin": "ince", "air": "hava", "made": "yaptı", "famous": "ünlü", "best": "en iyi", "climbers": "tırmanıcılar", "Earth": "Dünya", "Without": "olmadan", "help": "yardım", "almost": "neredeyse", "impossible": "imkansız", "foreign": "yabancı", "reach": "ulaşmak", "top": "zirve/tepe", "religious": "dindar", "people": "insanlar", "follow": "takip eder", "Buddhism": "Budizm", "word": "kelime", "become": "oldu", "symbol": "sembol", "strength": "güç", "bravery": "cesaret", "friendship": "dostluk", "world": "dünya", "adventure": "macera" },
    questions: [ {q:"Do the Sherpa live in the highest mountains of the Himalayas?", a_en:"Yes", a_tr:"Evet"}, {q:"Can their bodies breathe easily in thin air?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they the worst mountain climbers on Earth?", a_en:"No", a_tr:"Hayır"}, {q:"Is it easy for foreigners to climb Mount Everest with no Sherpas?", a_en:"No", a_tr:"Hayır"}, {q:"Are they religious people?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they follow Tibetan Buddhism?", a_en:"Yes", a_tr:"Evet"}, {q:"Has the word Sherpa become a symbol of bravery?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_Toraja.mp3"] = [{
    text: `The Toraja people live in the mountains of Sulawesi, Indonesia. They are famous for two things: their houses and their funerals. Their houses, called "Tongkonan," have roofs that look like giant boats. The most interesting part of their culture is how they treat death. When someone dies, the family keeps the body in the house for many months, treating them like they are just "sick." Then, they have a massive funeral festival with dancing and sacrifices. They even have a tradition where they take their ancestors out of their tombs to clean them.`,
    dict: { "live": "yaşarlar", "mountains": "dağlar", "famous": "ünlü", "two": "iki", "things": "şeyler", "houses": "evler", "funerals": "cenazeler", "called": "adlandırılan", "roofs": "çatılar", "look like": "gibi görünmek", "giant": "dev", "boats": "tekneler/kayıklar", "most": "en", "interesting": "ilginç", "part": "kısım", "culture": "kültür", "treat": "davranmak/muamele etmek", "death": "ölüm", "When": "zaman/olduğunda", "someone": "birisi", "dies": "ölür", "family": "aile", "keeps": "tutar", "body": "beden", "house": "ev", "many": "birçok", "months": "aylar", "treating": "davranarak", "just": "sadece", "sick": "hasta", "Then": "sonra", "massive": "muazzam", "funeral": "cenaze", "festival": "festival", "dancing": "dans", "sacrifices": "kurbanlar", "even": "hatta", "tradition": "gelenek", "take": "almak", "ancestors": "atalar", "out": "dışarı", "tombs": "mezarlar", "clean": "temizlemek" },
    questions: [ {q:"Do the Toraja people live in Indonesia?", a_en:"Yes", a_tr:"Evet"}, {q:"Do their houses have roofs that look like giant boats?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they bury a person immediately with no waiting?", a_en:"No", a_tr:"Hayır"}, {q:"Does the family keep the body in the house for months?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they treat the dead person like they are sick?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they have a massive funeral festival?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they clean their ancestors' tombs?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_Tuareg.mp3"] = [{
    text: `The Tuareg are a nomadic group that lives in the Sahara Desert. They are often called the "Blue People" because they wear indigo-blue veils and robes that stain their skin blue. In Tuareg culture, it is the men who wear the veils, not the women. They are legendary for surviving in the hottest parts of the desert using camel caravans. The Tuareg are also famous for their "Desert Blues" music, which uses electric guitars to tell stories about the sand. They are the true masters of the Sahara.`,
    dict: { "nomadic": "göçebe", "group": "grup", "lives": "yaşar", "Desert": "Çöl", "often": "sık sık", "called": "adlandırılan", "People": "İnsanlar", "because": "çünkü", "wear": "giyerler", "veils": "peçeler", "robes": "cübbeler", "stain": "lekelemek/boyamak", "skin": "deri/cilt", "blue": "mavi", "culture": "kültür", "men": "erkekler", "women": "kadınlar", "legendary": "efsanevi", "surviving": "hayatta kalma", "hottest": "en sıcak", "parts": "kısımlar", "using": "kullanarak", "camel": "deve", "caravans": "karavanlar/kafileler", "also": "ayrıca", "famous": "ünlü", "music": "müzik", "uses": "kullanır", "electric": "elektrikli", "guitars": "gitarlar", "tell": "anlatmak", "stories": "hikayeler", "about": "hakkında", "sand": "kum", "true": "gerçek", "masters": "ustalar" },
    questions: [ {q:"Are the Tuareg a nomadic group?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they called the 'Blue People'?", a_en:"Yes", a_tr:"Evet"}, {q:"Do their blue robes stain their skin?", a_en:"Yes", a_tr:"Evet"}, {q:"Do women wear no veils in their culture?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they survive using camel caravans?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for 'Desert Blues' music?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they use electric guitars to tell stories?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_Zulu.mp3"] = [{
    text: `The Zulu are the largest ethnic group in South Africa and have a powerful history. They became famous in the 1800s when their leader, Shaka Zulu, created a disciplined army. The Zulu warriors were known for their bravery and their "buffalo horn" battle tactics. Today, the Zulu are known for their colorful beadwork, which uses different colors to send secret messages about love. They are also famous for their energetic dancing and singing. The Zulu King still holds an important role in society. They are a symbol of strength and pride.`,
    dict: { "largest": "en büyük", "ethnic": "etnik", "group": "grup", "South": "Güney", "powerful": "güçlü", "history": "tarih", "became": "oldu", "famous": "ünlü", "leader": "lider", "created": "yarattı", "disciplined": "disiplinli", "army": "ordu", "warriors": "savaşçılar", "known": "bilinen", "bravery": "cesaret", "buffalo": "manda", "horn": "boynuz", "battle": "savaş", "tactics": "taktikler", "Today": "bugün", "colorful": "renkli", "beadwork": "boncuk işi", "uses": "kullanır", "different": "farklı", "colors": "renkler", "send": "göndermek", "secret": "gizli", "messages": "mesajlar", "about": "hakkında", "love": "sevgi/aşk", "also": "ayrıca", "energetic": "enerjik", "dancing": "dans", "singing": "şarkı söyleme", "King": "Kral", "still": "hala", "holds": "tutar/sahiptir", "important": "önemli", "role": "rol", "society": "toplum", "symbol": "sembol", "strength": "güç", "pride": "gurur" },
    questions: [ {q:"Are the Zulu the largest ethnic group in South Africa?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Shaka Zulu create a disciplined army?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the Zulu warriors known for their bravery?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use 'buffalo horn' battle tactics?", a_en:"Yes", a_tr:"Evet"}, {q:"Does their beadwork send secret messages about love?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they famous for quiet, slow dancing?", a_en:"No", a_tr:"Hayır"}, {q:"Does the Zulu King still hold an important role?", a_en:"Yes", a_tr:"Evet"} ]
}];
